owner: CoreMedia
repo: campaign.upptime

sites:
  - name: Delivery API
    url: https://api.campaigns.coremedia.io
    headers:
      - "Authorization: Bearer $HEADER_TOKEN_DELIVERY"
      - "Content-Type: application/json"
    method: POST
    body: '{"query":"query Check($site: String!, $channelType: String!) {campaignContent(site: $site, channelType: $channelType) {slots {assignment {items {id}}}}}","variables":{"site":"abc","channelType":"category-page"},"operationName":"Check"}'

  - name: Management API
    url: https://prod.campaign-management-prod.coremedia.services/graphql
    method: POST
    expectedStatusCodes:
      - 400
    headers:
      - "Content-Type: application/json"

  - name: Authorization API
    url: https://coremedia-jwt.api.coremedia.services/v1/config
    method: GET
    headers:
      - "Content-Type: application/json"

  - name: Validation API (Event Hub)
    url: https://prod-rest.campaign-management-prod.coremedia.services/eventHubHook
    method: POST
    headers:
      - "Authorization: Bearer $HEADER_TOKEN_VALIDATION"
      - "Content-Type: application/json"
    body: '{ "body": { "tenantId": "kayjrwt4", "sourceId": "live", "eventType": "CONTENT", "event": { "events": [ { "eventClass": "CONTENT", "eventType": "CONTENT_CREATED", "eventTimestamp": { "time": 1664214789291, "sequenceNumber": 19200, "subsequenceNumber": 1, "idTag": -1041910444 }, "contentId": "coremedia:///cap/content/5002", "contentUuid": "xxxxx4711xxxx", "contentType": "EditorProfile", "performerId": "coremedia:///cap/user/0", "name": "EditorProfile", "versionId": "coremedia:///cap/version/5002/1", "versionUuid": "10cd2978-25a0-46de-818e-083f6015b5fe", "folderId": "coremedia:///cap/content/227", "folderUuid": "268bb23b-aa92-40ef-a7c0-9ee2920720a3" } ] } } }'

status-website:
  baseUrl: /
  cname: status.campaigns.coremedia.io
  logoUrl: https://cdn.statically.io/gh/CoreMedia/campaign.upptime/main/assets/CM_logo_full_horizontal_fullwhite.svg
  favicon: https://cdn.statically.io/gh/CoreMedia/campaign.upptime/main/assets/CM_FavIcon.ico
  themeUrl: https://cdn.statically.io/gh/CoreMedia/campaign.upptime/main/assets/coremedia-campaign-status.css
  name: Campaigns Status Page
  introTitle: "Campaigns Status Page | CoreMedia"
  navbar:
    - title: Status
      href: /
    - title: Documentation
      href: https://documentation.coremedia.com/services/campaign-service/
    - title: CoreMedia.com
      href: https://www.coremedia.com/

i18n:
  footer: >
    [Sign Up for our industry-specific newsletters](https://www.coremedia.com/newsletter) to stay in touch with CoreMedia.<br>
    [Privacy](https://www.coremedia.com/privacy) | [Manage Preferences](https://www.coremedia.com/manage-preferences) | [Legal](https://www.coremedia.com/legal) | [Imprint](https://www.coremedia.com/imprint) | [Knowledge Center](https://www.coremedia.com/knowledge-center/overview)<br> 
    Copyright © CoreMedia GmbH, CoreMedia Corporation. All Rights Reserved.
