owner: CoreMedia
repo: campaign.upptime

sites:
  - name: Campaign Service Production CDN
    url: https://api.campaigns.coremedia.io
    headers:
      - "Authorization: Bearer $HEADER_TOKEN"
      - "Content-Type: application/json"
      - "$CAMPAIGN-SERVICE-PREVIEW-TOKEN: 1"

status-website:
  baseUrl: /campaign.upptime
  logoUrl: https://avatars.githubusercontent.com/u/182191?s=200&v=4
  name: Campaign Upptime
  introTitle: "**Campaigns Upptime** is a uptime monitor and status page about the Campaign Service."
  introMessage: You can see what services are available and what their average response time is. This information in also shown in dynamically generated Graphs.
  navbar:
    - title: Status
      href: /campaign.upptime/
  i18n:
    footer: ["**Sign Up for our industry-specific newsletters**"](https://www.coremedia.com/newsletter) to stay in touch with CoreMedia.
              [**Privacy**](https://www.coremedia.com/privacy) | [**Manage Preferences**](https://www.coremedia.com/manage-preferences) | [**Legal**](https://www.coremedia.com/legal) | [**Imprint**](https://www.coremedia.com/imprint) | [**Knowledge Center**](https://www.coremedia.com/knowledge-center/overview)
              Copyright © CoreMedia GmbH, CoreMedia Corporation. All Rights Reserved.

workflowSchedule:
  responseTime: "*/5 * * * *"