owner: CoreMedia
repo: campaign.upptime

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Campaign Service Production
    url: https://api.campaigns.coremedia.io
  - name: Campaign Service Development
    url: https://campaigns-dev.stellate.sh/
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  baseUrl: /campaign.upptime
  logoUrl: https://avatars.githubusercontent.com/u/182191?s=200&v=4
  name: Campaign Upptime
  introTitle: "**Campaigns Upptime** is a uptime monitor and status page about the Campaign Service."
  introMessage: This is a status page to show uptime information about the Campaign Service.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO