owner: CoreMedia
repo: campaign.upptime

sites:
  - name: Delivery API (cached)
    url: https://api.campaigns.coremedia.io
    headers:
      - "Authorization: Bearer $HEADER_TOKEN"
      - "Content-Type: application/json"
    body: '{"query":"query Check($site: String!, $channelType: String!) {campaignContent(site: $site, channelType: $channelType) {slots {assignment {items {id}}}}}","variables":{"site":"abc","channelType":"category-page"},"operationName":"Check"}'

  - name: Delivery API (uncached)
    url: https://api.campaigns.coremedia.io
    headers:
      - "Authorization: Bearer $HEADER_TOKEN"
      - "Content-Type: application/json"
      - "$CAMPAIGN_SERVICE_PREVIEW_TOKEN: 1"
    body: '{"query":"query Check($site: String!, $channelType: String!) {campaignContent(site: $site, channelType: $channelType) {slots {assignment {items {id}}}}}","variables":{"site":"abc","channelType":"category-page"},"operationName":"Check"}'

status-website:
  baseUrl: /campaign.upptime
  logoUrl: https://avatars.githubusercontent.com/u/182191?s=200&v=4
  name: CoreMedia Campaigns
  introTitle: "Status of CoreMedia Campaigns"
  navbar:
    - title: Status
      href: /campaign.upptime/
    - title: Documentation
      href: https://documentation.coremedia.com/services/campaign-service/
    - title: CoreMedia.com
      href: https://www.coremedia.com/
  i18n:
    footer: ["**Sign Up for our industry-specific newsletters**"](https://www.coremedia.com/newsletter) to stay in touch with CoreMedia.
              [**Privacy**](https://www.coremedia.com/privacy) | [**Manage Preferences**](https://www.coremedia.com/manage-preferences) | [**Legal**](https://www.coremedia.com/legal) | [**Imprint**](https://www.coremedia.com/imprint) | [**Knowledge Center**](https://www.coremedia.com/knowledge-center/overview)
              Copyright © CoreMedia GmbH, CoreMedia Corporation. All Rights Reserved.
workflowSchedule:
  responseTime: "*/5 * * * *"
