owner: CoreMedia
repo: campaign.upptime

sites:
  - name: Delivery API
    url: https://api.campaigns.coremedia.io
    headers:
      - "Authorization: Bearer $HEADER_TOKEN_DELIVERY"
      - "Content-Type: application/json"
    method: POST
    body: '{"query":"query Check($site: String!, $channelType: String!) {campaignContent(site: $site, channelType: $channelType) {slots {assignment {items {id}}}}}","variables":{"site":"abc","channelType":"category-page"},"operationName":"Check"}'

  - name: Management API
    url: https://prod.campaign-management-prod.coremedia.services/graphql
    method: POST
    expectedStatusCodes:
      - 400
    headers:
      - "Content-Type: application/json"

  - name: Authorization API
    url: https://coremedia-jwt.api.coremedia.services/v1/config
    method: GET
    headers:
      - "Content-Type: application/json"

  - name: Validation API (Event Hub)
    url: https://prod-rest.campaign-management-prod.coremedia.services/eventHubHook
    method: POST
    expectedStatusCodes:
      - 404
    headers:
      - "Authorization: Bearer $HEADER_TOKEN_VALIDATION"
      - "Content-Type: application/json"

status-website:
  baseUrl: /
  cname: status.campaigns.coremedia.io
  logoUrl: https://avatars.githubusercontent.com/u/182191?s=200&v=4
  themeUrl: https://raw.githubusercontent.com/CoreMedia/campaign.upptime/main/assets/coremedia.css
  name: CoreMedia Campaigns
  introTitle: "Status of CoreMedia Campaigns"
  navbar:
    - title: Status
      href: /
    - title: Documentation
      href: https://documentation.coremedia.com/services/campaign-service/
    - title: CoreMedia.com
      href: https://www.coremedia.com/

i18n:
  footer: >
    [Sign Up for our industry-specific newsletters](https://www.coremedia.com/newsletter) to stay in touch with CoreMedia.<br>
    [Privacy](https://www.coremedia.com/privacy) | [Manage Preferences](https://www.coremedia.com/manage-preferences) | [Legal](https://www.coremedia.com/legal) | [Imprint](https://www.coremedia.com/imprint) | [Knowledge Center](https://www.coremedia.com/knowledge-center/overview)<br> 
    Copyright © CoreMedia GmbH, CoreMedia Corporation. All Rights Reserved.

workflowSchedule:
  responseTime: "*/30 * * * *"
